source "%val{config}/config/formatters.kak" 

source "%val{config}/config/autosave.kak"

source "%val{config}/config/cursor.kak"

source "%val{config}/config/completion.kak"

add-highlighter global/ number-lines -hlcursor -relative -separator "  " -cursor-separator " |"
add-highlighter global/ show-matching
set-option global tabstop 2
set-option global indentwidth 2
colorscheme gruvbox-dark
