colorscheme gruvbox-dark
add-highlighter global/ number-lines -hlcursor -relative -separator "  " -cursor-separator " |"
add-highlighter global/ show-matching
set-option global tabstop 2
set-option global indentwidth 2

# set cursor to underline
hook global InsertIdle .* %{
  set-face window PrimaryCursor default,default+u
  set-face window PrimaryCursorEol default,default+u
  set-face window SecondaryCursor default,default+u
  set-face window SecondaryCursorEol default,default+u
  set-face window LineNumberCursor default,default+u
  set-face window PrimarySelection default,default+u
  set-face window SecondarySelection default,default+u
}

# set cursor to default
hook global NormalIdle .* %{
  set-face window PrimaryCursor default,default+r
  set-face window PrimaryCursorEol default,default+r
  set-face window SecondaryCursor default,default+r
  set-face window SecondaryCursorEol default,default+r
  set-face window LineNumberCursor default,default+r
  set-face window PrimarySelection default,default+r
  set-face window SecondarySelection default,default+r
}

hook global InsertCompletionShow .* %{
  try %{
    # this command temporarily removes cursors preceded by whitespace;
    # if there are no cursors left, it raises an error, does not
    # continue to execute the mapping commands, and the error is eaten
    # by the `try` command so no warning appears.
    execute-keys -draft 'h<a-K>\h<ret>'
    map window insert <tab> <c-n>
    map window insert <s-tab> <c-p>
    hook -once -always window InsertCompletionHide .* %{
      unmap window insert <tab> <c-n>
      unmap window insert <s-tab> <c-p>
    }
  }
}
