[[mgr.prepend_keymap]]
on   = [ "c", "a" ]
run  = "plugin ouch zip"
desc = "Archive selected files"

[[mgr.prepend_keymap]]
on = [ "D" ]
run = "remove --permanently --force"
desc = "Move the files to the trash"
