[mgr]
show_hidden = false
sort_by = "natural"
# sort_reverse = true
sort_sensitive = true
sort_dir_first = true
show_symlink = true

[preview]
image_quality = 90

[opener]
edit = [
	{ run = 'nvim %s', block = true },
]
foliate = [
  { run = 'foliate %s', orphan = true },
]
okular = [
  { run = 'okular %s', orphan = true },
]
playlist = [
  { run = 'mpv --playlist=%s', orphan = true },
]
latex = [
  { run = 'codium %s', orphan = true },
]
custom-mpv = [
  { run = 'mpv --loop-playlist=inf %s', orphan = true },
]
image-mpv = [
  { run = 'mpv --loop-file=inf --no-resume-playback %s', oprhan = true },
]


[open]
prepend_rules = [
	{ url = "*.epub", use = "foliate" },
  { url = "*.fb2", use = "foliate" },
  { url = "*.fb2.zip", use = "foliate" },
  { url = "*.mobi", use = "foliate" },

  { url = "*.srt", use = "edit" },

  { url = "*.pdf", use = "okular" },
  { url = "*.djvu", use = "okular" },

  { url = "*.plt", use = "playlist" },
  { mime = "{video}/*", use = "custom-mpv"},
  { mime = "{image}/*", use = "image-mpv"},

  { url = "*.tex", use = "latex" },
]

[plugin]
prepend_previewers = [
  { url = "*.md", run = "glow" },

  { url = "*.epub", run = "ebook-preview" },
  { url = "*.fb2", run =  "ebook-preview" },
  { url = "*.mobi", run = "ebook-preview" },
  { url = "*.fb2.zip", run = "ebook-preview" },

  { mime = "{image,audio,video}/*", run = "mediainfo"},
  { mime = "application/subrip", run = "mediainfo"},

  { mime = "application/*zip", run = "ouch" },
	{ mime = "application/tar", run = "ouch" },
	{ mime = "application/bzip2", run = "ouch" },
	{ mime = "application/7z-compressed", run = "ouch" },
	{ mime = "application/rar", run = "ouch" },
	{ mime = "application/xz", run = "ouch" },
	{ url = "*.zip", run = "ouch" },

  { mime = "application/bittorrent", run = "torrent-preview" },
]
