[manager]
show_hidden = false
sort_by = "natural"
sort_sensitive = true
sort_dir_first = true
show_symlink = true

[preview]
image_quality = 90

[opener]
edit = [
	{ run = 'nvim "$@"', block = true },
]
foliate = [
  { run = 'foliate "$@"', orphan = true },
]
okular = [
  { run = 'okular "$@"', orphan = true },
]
playlist = [
  { run = 'mpv --playlist="$@"', orphan = true },
]
latex = [
  { run = 'codium "$@"', orphan = true },
]


[open]
prepend_rules = [
	{ name = "*.epub", use = "foliate" },
  { name = "*.fb2", use = "foliate" },
  { name = "*.fb2.zip", use = "foliate" },
  { name = "*.mobi", use = "foliate" },

  { name = "*.pdf", use = "okular" },
  { name = "*.djvu", use = "okular" },
  { mime = "{image}/*", use = "okular"},

  { name = "*.plt", use = "playlist" },

  { name = "*.tex", use = "latex" },
]

[plugin]
prepend_previewers = [
  { name = "*.md", run = "glow" },

  { name = "*.epub", run = "ebook-preview" },
  { name = "*.fb2", run =  "ebook-preview" },
  { name = "*.mobi", run = "ebook-preview" },
  { name = "*.fb2.zip", run = "ebook-preview" },

  { mime = "{image,audio,video}/*", run = "mediainfo"},
  { mime = "application/subrip", run = "mediainfo"},

  { mime = "application/*zip", run = "ouch" },
	{ mime = "application/tar", run = "ouch" },
	{ mime = "application/bzip2", run = "ouch" },
	{ mime = "application/7z-compressed", run = "ouch" },
	{ mime = "application/rar", run = "ouch" },
	{ mime = "application/xz", run = "ouch" },
	{ name = "*.zip", run = "ouch" },

  { mime = "application/bittorrent", run = "torrent-preview" },
]
